## Customers

CREATE TABLE api_customers (

    customer_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    customer_code VARCHAR2(50)
        NOT NULL,

    customer_name VARCHAR2(200)
        NOT NULL,

    email VARCHAR2(320)
        NOT NULL,

    phone VARCHAR2(50),

    status VARCHAR2(20)
        DEFAULT 'ACTIVE'
        NOT NULL,

    created_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    updated_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_api_customers
        PRIMARY KEY (customer_id),

    CONSTRAINT uq_api_customer_code
        UNIQUE (customer_code),

    CONSTRAINT uq_api_customer_email
        UNIQUE (email),

    CONSTRAINT chk_customer_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE',
                'SUSPENDED'
            )
        )
);

---

## Products

CREATE TABLE api_products (

    product_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    product_code VARCHAR2(50)
        NOT NULL,

    product_name VARCHAR2(200)
        NOT NULL,

    category VARCHAR2(100),

    price NUMBER(12,2)
        NOT NULL,

    stock_quantity NUMBER
        DEFAULT 0,

    status VARCHAR2(20)
        DEFAULT 'ACTIVE',

    created_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    updated_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_api_products
        PRIMARY KEY (product_id),

    CONSTRAINT uq_api_product_code
        UNIQUE (product_code),

    CONSTRAINT chk_product_price
        CHECK (price >= 0),

    CONSTRAINT chk_product_stock
        CHECK (stock_quantity >= 0)
);

---

## Orders

CREATE TABLE api_orders (

    order_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    order_number VARCHAR2(50)
        NOT NULL,

    customer_id NUMBER
        NOT NULL,

    order_status VARCHAR2(30)
        DEFAULT 'PENDING',

    total_amount NUMBER(14,2)
        DEFAULT 0,

    created_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    updated_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_api_orders
        PRIMARY KEY (order_id),

    CONSTRAINT uq_order_number
        UNIQUE (order_number),

    CONSTRAINT fk_order_customer
        FOREIGN KEY (customer_id)
        REFERENCES api_customers(customer_id)
);

---

## Order Items

CREATE TABLE api_order_items (

    order_item_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    order_id NUMBER
        NOT NULL,

    product_id NUMBER
        NOT NULL,

    quantity NUMBER
        NOT NULL,

    unit_price NUMBER(12,2)
        NOT NULL,

    line_total NUMBER(14,2)
        NOT NULL,

    CONSTRAINT pk_api_order_items
        PRIMARY KEY (order_item_id),

    CONSTRAINT fk_item_order
        FOREIGN KEY (order_id)
        REFERENCES api_orders(order_id),

    CONSTRAINT fk_item_product
        FOREIGN KEY (product_id)
        REFERENCES api_products(product_id),

    CONSTRAINT chk_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_item_price
        CHECK (unit_price >= 0)
);

---

## API Audit Log

CREATE TABLE api_audit_log (

    audit_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    request_id VARCHAR2(100),

    endpoint VARCHAR2(500),

    http_method VARCHAR2(20),

    username VARCHAR2(200),

    status_code NUMBER,

    request_timestamp TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    response_time_ms NUMBER,

    error_message VARCHAR2(4000),

    CONSTRAINT pk_api_audit
        PRIMARY KEY (audit_id)
);

---

## API Error Log

CREATE TABLE api_error_log (

    error_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    request_id VARCHAR2(100),

    error_code VARCHAR2(100),

    error_message VARCHAR2(4000),

    stack_trace CLOB,

    created_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_api_error_log
        PRIMARY KEY (error_id)
);

---

