-- =========================================================
-- SOURCE TABLES
-- =========================================================

CREATE TABLE src_customers (

    customer_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    customer_name VARCHAR2(200)
        NOT NULL,

    email VARCHAR2(320),

    city VARCHAR2(100),

    country VARCHAR2(100),

    customer_segment VARCHAR2(50),

    created_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    updated_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_src_customers
        PRIMARY KEY (customer_id)
);


CREATE TABLE src_products (

    product_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    product_name VARCHAR2(200)
        NOT NULL,

    category VARCHAR2(100),

    subcategory VARCHAR2(100),

    unit_price NUMBER(12,2),

    active_flag CHAR(1)
        DEFAULT 'Y',

    created_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    updated_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_src_products
        PRIMARY KEY (product_id)
);


CREATE TABLE src_orders (

    order_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    customer_id NUMBER,

    order_date DATE,

    city VARCHAR2(100),

    country VARCHAR2(100),

    status VARCHAR2(30),

    created_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    updated_at TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_src_orders
        PRIMARY KEY (order_id)
);


CREATE TABLE src_order_items (

    order_item_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    order_id NUMBER
        NOT NULL,

    product_id NUMBER
        NOT NULL,

    quantity NUMBER(12,2),

    unit_price NUMBER(12,2),

    discount_amount NUMBER(12,2)
        DEFAULT 0,

    CONSTRAINT pk_src_order_items
        PRIMARY KEY (order_item_id)
);
