CREATE TABLE dim_customer (

    customer_key NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    customer_id NUMBER
        NOT NULL,

    customer_name VARCHAR2(200),

    email VARCHAR2(320),

    city VARCHAR2(100),

    country VARCHAR2(100),

    customer_segment VARCHAR2(50),

    effective_from DATE
        NOT NULL,

    effective_to DATE,

    current_flag CHAR(1)
        DEFAULT 'Y',

    CONSTRAINT pk_dim_customer
        PRIMARY KEY (customer_key)
);
