## Customer Dimension
    
CREATE TABLE dim_customer (

    customer_key NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    customer_id NUMBER
        NOT NULL,

    customer_name VARCHAR2(200),

    email VARCHAR2(320),

    city VARCHAR2(100),

    country VARCHAR2(100),

    customer_segment VARCHAR2(50),

    effective_from DATE
        NOT NULL,

    effective_to DATE,

    current_flag CHAR(1)
        DEFAULT 'Y',

    CONSTRAINT pk_dim_customer
        PRIMARY KEY (customer_key)
);

---

## Product Dimension

CREATE TABLE dim_product (

    product_key NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    product_id NUMBER
        NOT NULL,

    product_name VARCHAR2(200),

    category VARCHAR2(100),

    subcategory VARCHAR2(100),

    unit_price NUMBER(12,2),

    active_flag CHAR(1),

    effective_from DATE
        NOT NULL,

    effective_to DATE,

    current_flag CHAR(1)
        DEFAULT 'Y',

    CONSTRAINT pk_dim_product
        PRIMARY KEY (product_key)
);

---

## Date Dimension

CREATE TABLE dim_date (

    date_key NUMBER
        PRIMARY KEY,

    calendar_date DATE
        NOT NULL,

    day_number NUMBER,

    month_number NUMBER,

    month_name VARCHAR2(20),

    quarter_number NUMBER,

    year_number NUMBER,

    week_number NUMBER,

    day_name VARCHAR2(20),

    is_weekend CHAR(1)
);

---

## Location Dimension

CREATE TABLE dim_location (

    location_key NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    city VARCHAR2(100),

    country VARCHAR2(100),

    region VARCHAR2(100),

    CONSTRAINT pk_dim_location
        PRIMARY KEY (location_key)
);
