-- =========================================================
-- FACT SALES
-- =========================================================

CREATE TABLE fact_sales (

    sales_key NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    order_id NUMBER
        NOT NULL,

    order_item_id NUMBER
        NOT NULL,

    date_key NUMBER
        NOT NULL,

    customer_key NUMBER
        NOT NULL,

    product_key NUMBER
        NOT NULL,

    location_key NUMBER
        NOT NULL,

    quantity NUMBER(12,2),

    unit_price NUMBER(12,2),

    discount_amount NUMBER(12,2),

    gross_amount NUMBER(14,2),

    net_amount NUMBER(14,2),

    load_timestamp TIMESTAMP
        DEFAULT SYSTIMESTAMP,

    CONSTRAINT pk_fact_sales
        PRIMARY KEY (sales_key),

    CONSTRAINT fk_fact_date
        FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT fk_fact_customer
        FOREIGN KEY (customer_key)
        REFERENCES dim_customer(customer_key),

    CONSTRAINT fk_fact_product
        FOREIGN KEY (product_key)
        REFERENCES dim_product(product_key),

    CONSTRAINT fk_fact_location
        FOREIGN KEY (location_key)
        REFERENCES dim_location(location_key)
);
